### ISSUE TITLE
Create labels on issues

### ISSUE THREAD

**Issue by dsyme** [baronfel/fsharp-lang-suggestions#12]
Assuming we move to github issues, we should also create labels on each of the issues (declined, in progress etc.)

https://github.com/baronfel/fsharp-lang-suggestions/issues/11

**Comment by cloudRoutine** [comment]
that's the plan, I didn't get the chance to work on it yesterday.
the json file has all the content from all of the entries, we planned on generating md docs to archive all of them and the suggestions that haven't been declined or completed will be created as issues.
the closed and completed suggestions could be added as issues and then closed if that's what you prefer.

**Comment by dsyme** [comment]
> the closed and completed suggestions could be added as issues and then closed if that's what you prefer

Yes, that would be best, thanks

**Comment by baronfel** [comment]
This is actually in progress and pretty close to done.

At the moment there's a bug in the code that streamlines comments and admin responses into a single comment stream on the issue. I've been iterating on issue generation over at baronfel/fsharp-langtestbed if you want to see how they look

**Comment by baronfel** [comment]
marking this one as done based on the code we've got right now
